version: '3.8'

services:
  # Redis缓存
  redis:
    image: redis:7-alpine
    container_name: blog_redis_prod
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - blog_network
    command: redis-server --appendonly yes --requirepass "${REDIS_PASSWORD}"

  # 后端API服务
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: blog_backend_prod
    restart: unless-stopped
    environment:
      - GIN_MODE=release
      - DOMAIN=www.godepth.top
      - ENVIRONMENT=production
      - DB_HOST=host.docker.internal
      - DB_PORT=3306
      - DB_USER=${DB_USER:-root}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME:-blog_db}
      - DB_TIMEZONE=Asia/Shanghai
      - DB_SSLMODE=disable
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - API_BASE_URL=https://www.godepth.top
      - VITE_API_BASE_URL=https://www.godepth.top
      - JWT_SECRET=${JWT_SECRET}
      - ALLOWED_ORIGINS=https://www.godepth.top,http://localhost:5173
    ports:
      - "3001:3001"
    depends_on:
      redis:
        condition: service_started
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - blog_network
    volumes:
      - ./data/uploads:/app/uploads
      - ./data/search_index:/app/search_index
      - ./frontend/public/books:/app/books

  # 前端服务
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
      args:
        - VITE_API_BASE_URL=${VITE_API_BASE_URL}
    container_name: blog_frontend_prod
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "8080:8080"
    networks:
      - blog_network
    volumes:
      - ./frontend/public/books:/usr/share/nginx/html/books

volumes:
  redis_data:
    driver: local

networks:
  blog_network:
    driver: bridge