services:
  # Redis缓存（可选）
  redis:
    image: redis:7-alpine
    container_name: blog_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - blog_network
    command: redis-server --appendonly yes

  # 后端API服务
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: blog_backend
    restart: unless-stopped
    environment:
      - GIN_MODE=debug
      - DB_HOST=host.docker.internal
      - DB_PORT=3306
      - DB_USER=${DB_USER:-root}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME:-blog_db}
      - DB_TIMEZONE=Asia%2FShanghai
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "3001:3001"
    depends_on:
      redis:
        condition: service_started
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - blog_network
    volumes:
      - ./backend/uploads:/app/uploads

  # 前端服务
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: blog_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - API_BASE_URL=http://www.godepth.top
      - VITE_API_BASE_URL=/api
    depends_on:
      - backend
    networks:
      - blog_network

  # Nginx反向代理（生产环境）
  nginx:
    image: nginx:alpine
    container_name: blog_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/ssl:/etc/nginx/ssl
      - ./backend/uploads:/var/www/uploads
    depends_on:
      - frontend
      - backend
    networks:
      - blog_network
    profiles:
      - production

volumes:
  redis_data:
    driver: local

networks:
  blog_network:
    driver: bridge