-- 创建算法资产表
CREATE TABLE IF NOT EXISTS algorithm_assets (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    slug VARCHAR(255) NOT NULL UNIQUE,
    leetcode_id BIGINT UNSIGNED NULL,
    source_url VARCHAR(500) NULL,
    source_dir_name VARCHAR(255) NULL,
    description TEXT,
    difficulty VARCHAR(20) NULL,
    tags LONGTEXT,
    status VARCHAR(20) NOT NULL DEFAULT 'draft',
    summary_note TEXT,
    weak_points TEXT,
    review_status VARCHAR(20) NOT NULL DEFAULT 'new',
    next_review_at DATETIME NULL,
    primary_markdown_file_id BIGINT UNSIGNED NULL,
    primary_video_file_id BIGINT UNSIGNED NULL,
    author_id BIGINT UNSIGNED NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    INDEX idx_algorithm_assets_slug (slug),
    INDEX idx_algorithm_assets_status (status),
    INDEX idx_algorithm_assets_leetcode (leetcode_id),
    INDEX idx_algorithm_assets_source_dir (source_dir_name),
    INDEX idx_algorithm_assets_review_status (review_status),
    INDEX idx_algorithm_assets_next_review (next_review_at),
    INDEX idx_algorithm_assets_author (author_id),
    CONSTRAINT fk_algorithm_assets_author FOREIGN KEY (author_id) REFERENCES users(id) ON DELETE CASCADE
);

-- 创建算法资产文件表
CREATE TABLE IF NOT EXISTS algorithm_asset_files (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    asset_id BIGINT UNSIGNED NOT NULL,
    file_kind VARCHAR(20) NOT NULL,
    role VARCHAR(40) NULL,
    display_name VARCHAR(255) NOT NULL,
    original_name VARCHAR(255) NOT NULL,
    sort_order INT NOT NULL DEFAULT 0,
    is_primary BOOLEAN NOT NULL DEFAULT FALSE,
    markdown_content LONGTEXT,
    storage_url VARCHAR(500) NULL,
    mime_type VARCHAR(100) NULL,
    size_bytes BIGINT NOT NULL DEFAULT 0,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    INDEX idx_algorithm_asset_files_asset (asset_id),
    INDEX idx_algorithm_asset_files_kind (file_kind),
    INDEX idx_algorithm_asset_files_role (role),
    INDEX idx_algorithm_asset_files_sort (asset_id, file_kind, sort_order),
    INDEX idx_algorithm_asset_files_primary (asset_id, is_primary),
    CONSTRAINT fk_algorithm_asset_files_asset FOREIGN KEY (asset_id) REFERENCES algorithm_assets(id) ON DELETE CASCADE
);
